// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/Fermekoo/orderin-api/db/models"
)

// CategoriesRepo is an autogenerated mock type for the CategoriesRepo type
type CategoriesRepo struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *CategoriesRepo) GetAll(ctx context.Context) ([]models.Categories, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Categories
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Categories, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Categories); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Categories)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCategoriesRepo creates a new instance of CategoriesRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoriesRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoriesRepo {
	mock := &CategoriesRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
