name: orderin-api-workflows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Build
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: gokapster
        ports:
          - 3307:3307
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Set up go 1.x
      uses: actions/setup-go@v2
      with: 
        go-version: ^1.19
      id: go
    
    - name: Checkout code into the GO module directory
      uses: actions/checkout@v2

    - name: Install golang migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/
        which migrate

    - name: db migrations
      run: |
        export DATABASE_URL="mysql://root:root@tcp(0.0.0.0:3307)/gokapster"
        export MIGRATE_PATH="db/migrations"
        migrate -database $DATABASE_URL -path $MIGRATE_PATH -verbose up

    - name: test
      run: make test
      



